language: node_js
node_js:
  - 10.15.3
install:
  - yarn install
before_script:
  - node --version
  - yarn --version
  - node_modules/.bin/newman --version
script:
  - node_modules/.bin/newman run postcards_postman_collection.json
  - npm run cypress:run
